### ISSUE TITLE
cant see any gui

### ISSUE THREAD

**Issue by Hackerhashdev** [codingminecraft/MarioYoutube#10]
help pls my screen is full hd and when i run the program it shows only that
![image](https://user-images.githubusercontent.com/75426945/155497679-4b6be983-6907-4a7c-aef2-3fa80989a29a.png)

**Comment by abdulmk787** [comment]
DId you get a fix for it?

**Comment by codingminecraft** [comment]
You can delete the imgui.ini file to reset the imgui settings. 

Since this is just example code for the tutorial series I did not write it with the intention of shipping it. You can download the original proof of concept, which was coded with shipping the final product to end users in mind, at itch.io using the download link in the first or second episode of the series.
