### ISSUE TITLE
Gitignore fonts breaks imgui dependancy

### ISSUE THREAD

**Issue by athaun** [codingminecraft/MarioYoutube#6]
in the package jade.ImGuiLayer.java > call to
```java
fontAtlas.addFontFromFileTTF("assets/fonts/segoeui.ttf", 32, fontConfig);
```
breaks because `assets/fonts/*` is in the .gitignore
Commenting it out works fine because imgui defaults to a fallback font.

**Comment by codingminecraft** [comment]
Yea I added segoeui.ttf to the gitignore because I believe it's copyrighted. I've added an if-check around that to make sure the file exists so that ImGui will default to the appropriate font if necessary. https://github.com/codingminecraft/MarioYoutube/blob/2fef4a6630b0dad8bda30ce991322d5d250251a4/src/main/java/jade/ImGuiLayer.java#L137
